version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: fast-messages:1:1
      #HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      #KAFKA_ADVERTISED_HOST_NAME: 10.0.2.15
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: kafka-producer
    container_name: kafka-producer
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/producer/Dockerfile
    links:
      - kafka:kafka
    tty: true
    depends_on:
      - kafka
    environment:
      BROKER_LIST: kafka:9092
    #network_mode: "host"

  consumer:
    image: kafka-consumer
    container_name: kafka-consumer
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/consumer/Dockerfile
    links:
      - kafka:kafka
    tty: true
    depends_on:
      - producer
    environment:
      BROKER_LIST: kafka:9092
    #network_mode: "host"
