version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.10
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:2.12-2.3.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - "9191:9091"
      - "9192:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INT_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_PLAINTEXT
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9192
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INT_PLAINTEXT://_{HOSTNAME_COMMAND}:9192,EXTERNAL_PLAINTEXT://10.81.81.99:9191
      KAFKA_LISTENERS: INT_PLAINTEXT://0.0.0.0:9092,EXTERNAL_PLAINTEXT://0.0.0.0:9091
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka:2.12-2.3.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - "9291:9091"
      - "9292:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INT_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_PLAINTEXT
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9192
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INT_PLAINTEXT://_{HOSTNAME_COMMAND}:9292,EXTERNAL_PLAINTEXT://10.81.81.99:9291
      KAFKA_LISTENERS: INT_PLAINTEXT://0.0.0.0:9092,EXTERNAL_PLAINTEXT://0.0.0.0:9091
      KAFKA_BROKER_ID: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: wurstmeister/kafka:2.12-2.3.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - "9391:9091"
      - "9392:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INT_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_PLAINTEXT
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9192
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INT_PLAINTEXT://_{HOSTNAME_COMMAND}:9392,EXTERNAL_PLAINTEXT://10.81.81.99:9391
      KAFKA_LISTENERS: INT_PLAINTEXT://0.0.0.0:9092,EXTERNAL_PLAINTEXT://0.0.0.0:9091
      KAFKA_BROKER_ID: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: kafka-producer
    container_name: kafka-producer
    restart: on-failure
    build:
      context: ..
      dockerfile: ./docker/producer/Dockerfile
    tty: true
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      BROKER_LIST: kafka1:9092,kafka2:9092,kafka3:9092
      TOPIC: fast-messages
      PARTITIONS: 3
      REPLICATION_FACTOR: 1

  consumer:
    image: kafka-consumer
    container_name: kafka-consumer
    restart: unless-stopped
    tty: true
    depends_on:
      - producer
    environment:
      BROKER_LIST: kafka1:9092,kafka2:9092,kafka3:9092
      THREADS: 3
